### ISSUE TITLE
Requests forwarded to other codePackage

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/service-fabric-mesh-preview#159]
I have an application with following setup:
- `Containo.Orders.API` service that is the customer-facing endpoint
    - `Containo.Orders.API` code package which is my API running on port 80. This one has an endpoint defined for port 80.
    - `Containo.Orders.Validator` code package which is a sidecar for my API which was supposed to run on 81, but was running on 80.
- `Containo.Orders.QueueProcessor` service processing messages
- `Containo.Network.Public` network which exposes the endpoint defined in my API service & code package and will forward traffic from port 1337 to it.

When I was browsing to `<public-ip>:1337/swagger` I was suprised to see the OpenAPI specs for my validator container, not my API container. Turns out this was because of a misconfiguration (`ASPNETCORE_URLS`) on my validator code package.

This makes me think:
- This means that the endpoints are actually giving access to every code package inside a service
- If so, why is the endpoint configuration on a code package and not on the service itself?

## Spec
```yaml
{
    "$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "Application.Name": {
            "type": "string",
            "defaultValue": "Containo.Orders",
            "metadata": {
                "description": "Name of the Service Fabric Application"
            }
        },
        "Application.Description": {
            "type": "string",
            "defaultValue": "Application that is used to create orders",
            "metadata": {
                "description": "Description of the Service Fabric Application"
            }
        },
        "Application.Network.Name": {
            "type": "string",
            "defaultValue": "Containo.Network.Public",
            "metadata": {
                "description": "Name of network to use in which your Service Fabric Application will be"
            }
        },
        "Region": {
            "type": "string",
            "defaultValue": "eastus",
            "metadata": {
                "description": "Region in which the resources will be deployed"
            }
        }
    },
    "resources": [
        {
            "apiVersion": "2018-03-01-privatepreview",
            "name": "[parameters('Application.Network.Name')]",
            "type": "Microsoft.ServiceFabric/networks",
            "location": "[parameters('Region')]",
            "dependsOn": [],
            "properties": {
                "description": "Public network for Containo",
                "addressPrefix": "10.0.0.4/22",
                "ingressConfig": {
                    "qosLevel": "bronze",
                    "layer4": [
                        {
                            "publicPort": "1337",
                            "applicationName": "[parameters('Application.Name')]",
                            "serviceName": "Containo.Orders.API",
                            "endpointName": "HTTP-Public-APIs-Orders"
                        }
                    ]
                }
            }
        },
        {
            "apiVersion": "2018-03-01-privatepreview",
            "name": "[parameters('Application.Name')]",
            "type": "Microsoft.ServiceFabric/applications",
            "location": "[parameters('Region')]",
            "properties": {
                "description": "[parameters('Application.Description')]",
                "services": [
                    {
                        "name": "Containo.Orders.API",
                        "properties": {
                            "description": "Containo Orders API",
                            "osType": "linux",
                            "codePackages": [
                                {
                                    "name": "Containo.Orders.API",
                                    "image": "tomkerkhove/containo.services.orders.api:0.1.0.19",
                                    "endpoints": [
                                        {
                                            "name": "HTTP-Public-APIs-Orders",
                                            "port": 80
                                        }
                                    ],
                                    "environmentVariables": [],
                                    "resources": {
                                        "requests": {
                                            "cpu": 1,
                                            "memoryInGB": 1
                                        }
                                    }
                                },
                                {
                                    "name": "Containo.Orders.Validator",
                                    "image": "tomkerkhove/containo.services.orders.validator:0.1.0.19",
                                    "endpoints": [],
                                    "environmentVariables": [],
                                    "resources": {
                                        "requests": {
                                            "cpu": 1,
                                            "memoryInGB": 1
                                        }
                                    }
                                }
                            ],
                            "replicaCount": 1,
                            "networkRefs": [
                                {
                                    "name": "[resourceId('Microsoft.ServiceFabric/networks', parameters('Application.Network.Name'))]"
                                }
                            ]
                        }
                    },
                    {
                        "name": "Containo.Orders.QueueProcessor",
                        "properties": {
                            "description": "Queue processor that will handle the order messages",
                            "osType": "linux",
                            "codePackages": [
                                {
                                    "name": "Containo.Orders.QueueProcessor",
                                    "image": "tomkerkhove/containo.services.orders.queueprocessor:0.1.0.19",
                                    "endpoints": [],
                                    "environmentVariables": [],
                                    "resources": {
                                        "requests": {
                                            "cpu": 1,
                                            "memoryInGB": 1
                                        }
                                    }
                                }
                            ],
                            "replicaCount": 1,
                            "networkRefs": [
                                {}
                            ]
                        }
                    }
                ]
            }
        }
    ]
}
```
