### ISSUE TITLE
Can gateway http rules be declared in YAML?

### ISSUE THREAD

**Issue by aloneguid** [Azure/service-fabric-mesh-preview#308]
The following definition seems to fail when deploying from VS to local cluster:

```yaml
    http:
      name: web
      port: 80
      hosts:
        - name: "*"
          routes:
          - match:
              path:
                value: "/first"
                rewrite: "/"
                type: Prefix
            destination:
              applicationName: TwoApis
              serviceName: Api1
              endpointName: Api1Listener
```
