### ISSUE TITLE
Gateway can't expose two endpoints on different ports

### ISSUE THREAD

**Issue by markheath** [Azure/service-fabric-mesh-preview#315]
I've created a JSON application template and want to use a gateway to expose two endpoints publicly.
I have two services (voteService and resultService) each with an endpoint (VoteListener and ResultListener) and want to expose them both on different ports. I can't simply use two routes (as shown in the ["ingress" sample](https://github.com/Azure-Samples/service-fabric-mesh/blob/master/templates/ingress/meshingress.windows.json)) for the same port as my services don't work correctly with a route prefix.

I've tried various combinations of http and tcp gateway configurations, but every time I deploy only one of the two endpoints is accessible (sometimes the vote one, sometimes the result one).

My most recent attempt is this:

```
        "http": [
          {
            "name": "vote",
            "port": 80,
            "hosts": [
              {
                "name": "*",
                "routes": [
                  {
                    "name":  "voteRoute",
                    "match": {
                      "path": {
                        "value": "/",
                        "rewrite": "/",
                        "type": "Prefix"
                      }
                    },
                    "destination": {
                      "applicationName": "votingApp",
                      "serviceName": "voteService",
                      "endpointName": "VoteListener"
                    }
                  }
                ]
              }
            ]
          },
          {
            "name": "result",
            "port": 8082,
            "hosts": [
              {
                "name": "*",
                "routes": [
                  {
                    "name": "resultRoute",
                    "match": {
                      "path": {
                        "value": "/",
                        "rewrite": "/",
                        "type": "Prefix"
                      }
                    },
                    "destination": {
                      "applicationName": "votingApp",
                      "serviceName": "resultService",
                      "endpointName": "ResultListener"
                    }
                  }
                ]
              }
            ]
          }
        ],
        "tcp": [
          {
            "name": "tcpVote",
            "port": 8080,
            "destination": {
              "applicationName": "votingApp",
              "serviceName": "voteService",
              "endpointName": "VoteListener"
            }
          },
          {
            "name": "tcpResult",
            "port": 8081,
            "destination": {
              "applicationName": "votingApp",
              "serviceName": "resultService",
              "endpointName": "ResultListener"
            }
          }
        ]
```

And this exposed the Result service on both 8081 and 8082 but the vote service was not accessible on 80 or 8080.

The containers are windows if that makes any difference. From examining the container logs, all containers seem to have started successfully.

I also tried defining two different gateways each exposing one service but that also didn't work.

Is this a limitation of the Service Fabric Mesh preview, or am I doing something fundamentally wrong?

**Comment by guibirow** [comment]
For security reasons I didn't run your container images, I've modified the HelloWorld sample and added and extra service and the gateway added multiple routes (1 http for each service and 1 tcp for each), I can confirm All routes worked "without issues":

This is my gateway configuration:

```
    {
      "apiVersion": "2018-09-01-preview",
      "name": "helloWorldGateway",
      "type": "Microsoft.ServiceFabricMesh/gateways",
      "location": "[parameters('location')]",
      "dependsOn": [
        "Microsoft.ServiceFabricMesh/networks/helloWorldNetwork"
      ],
      "properties": {
        "description": "Service Fabric Mesh Gateway for HelloWorld sample.",
        "sourceNetwork": {
          "name": "Open"
        },
        "destinationNetwork": {
          "name": "[resourceId('Microsoft.ServiceFabricMesh/networks', 'helloWorldNetwork')]"
        },
        "http": [
          {
            "name": "web",
            "port": 81,
            "hosts": [
              {
                "name": "*",
                "routes": [
                  {
                    "name":  "helloRoute",
                    "match": {
                      "path": {
                        "value": "/",
                        "rewrite": "/",
                        "type": "Prefix"
                      }
                    },
                    "destination": {
                      "applicationName": "helloWorldApp",
                      "serviceName": "helloWorldService",
                      "endpointName": "helloWorldListener"
                    }
                  }
                ]
              }
            ]
          },
          {
            "name": "kuard",
            "port": 82,
            "hosts": [
              {
                "name": "*",
                "routes": [
                  {
                    "name":  "kuardRoute",
                    "match": {
                      "path": {
                        "value": "/",
                        "rewrite": "/",
                        "type": "Prefix"
                      }
                    },
                    "destination": {
                      "applicationName": "helloWorldApp",
                      "serviceName": "kuardService",
                      "endpointName": "kuardListener"
                    }
                  }
                ]
              }
            ]
          }
        ],
        "tcp": [
          {
            "name": "web",
            "port": 80,
            "destination": {
              "applicationName": "helloWorldApp",
              "serviceName": "helloWorldService",
              "endpointName": "helloWorldListener"
            }
          },
          {
            "name": "kuard",
            "port": 8080,
            "destination": {
              "applicationName": "helloWorldApp",
              "serviceName": "kuardService",
              "endpointName": "kuardListener"
            }
          }
        ]
      }
    }
```

When I hit the endpoints:

`http://gatewayip:80` and `http://gatewayip:81` routes to _helloWorldService_

`http://gatewayip:82` and `http://gatewayip:8080` routes to kuardService

PS: At the top, I gave an emphasis on "without issues", because seems that the gateway does not work while being upgraded, this issue is being tracked on https://github.com/Azure/service-fabric-mesh-preview/issues/304

**Comment by guibirow** [comment]
Not sure about this issue, make sure you are not hitting the max quotas described [here ](https://docs.microsoft.com/en-us/azure/service-fabric-mesh/service-fabric-mesh-faq#quota-and-cost)

**Comment by sridmad** [comment]
@markheath, Can you open a different issue for IPAddressProviderAddressRangeExhausted error? 

**Windows vs Linux containers:** Depending on the base image used for Windows image, it can take a while to download the image and hence not reachable for a while. Unless you need Windows Server Core base image, use one of the nanoserver images as base image. Some times I have seen images based on Windows Server core take upwards of 5 minutes to download.

We will update the Hello World conatiner to use nano server to speed up download and activation.

>>>
I get "upstream connect error or disconnect/reset before headers"
>>>
Does it work after a while. This most probably means the container is not yet activated completely.

**Comment by aloneguid** [comment]
I've just tested and it works for me, two services on different ports are accessible. My gateway resource:

```yaml
gateway:
  schemaVersion: 1.0.0-preview2
  name: TwoApisGateway
  properties:
    description: TwoApis Gateway Resource
    sourceNetwork:
      name: Open
    destinationNetwork:
      name: TwoApisNetwork
#    tcp:
#      - name: FactsWebSiteTCP
#        port: "[parameters('FactsWebSite_ingressport')]"
#        destination:
#          applicationName: TwoApis
#          serviceName: FactsWebSite
#          endpointName: FactsWebSiteListener
#      - name: FactsApiTCP
#        port: "[parameters('FactsApi_ingressport')]"
#        destination:
#          applicationName: TwoApis
#          serviceName: FactsApi
#          endpointName: FactsApiListener
    http:
      - name: FactsApiHTTP
        port: 80
        hosts:
          - name: "*"
            routes:
              - name: api
                match:
                  path:
                    value: "/api/"
                    rewrite: "/"
                    type: Prefix
                destination:
                  applicationName: TwoApis
                  serviceName: FactsApi
                  endpointName: FactsApiListener
      - name: FactsWebHTTP
        port: 81
        hosts:
          - name: "*"
            routes:
              - name: web
                match:
                  path:
                    value: "/"
                    rewrite: "/"
                    type: Prefix
                destination:
                  applicationName: TwoApis
                  serviceName: FactsWebSite
                  endpointName: FactsWebSiteListener     
```
