### ISSUE TITLE
System.Net.Sockets.SocketException on outbound HTTP calls

### ISSUE THREAD

**Issue by rangp** [Azure/service-fabric-mesh-preview#332]
Hi,

I'm playing around with service fabric mesh and wanted to make a basic http call in a console app that I created using the VS template for service fabric mesh:

```
            var client = new HttpClient();
            client.GetAsync("https://www.google.com").GetAwaiter().GetResult();
```

However this produces:
**System.Net.Sockets.SocketException : 'The requested service provider could not be loaded or initialized'**

My network.yaml looks as follows:

```
## Network definition ##
network:
  schemaVersion: 1.0.0-preview2
  name: Application1Network
  properties:
    description: Application1Network description.
    networkAddressPrefix: 10.192.0.0/16
    kind: Local
```

What do I have to chance in order to make it work? Unfortunately I couldn't find any documentation about outbound connections in service fabric mesh.

Kind regards
Peter
