### ISSUE TITLE
Reliable Volumes ignored

### ISSUE THREAD

**Issue by aloneguid** [Azure/service-fabric-mesh-preview#336]
It seems that reliable volume resource is completely ignored on deployment. Local cluster just hangs and fails, Azure deployment succeeds, however there are no volume resources listed on the portal. Here is my yaml definition:

```yaml
...
        codePackages:
        - name: xxx
          image: xxx:dev
          volumes:
          - name: sfvol
            creationParameters:
              kind: ServiceFabricVolumeDisk
              sizeDisk: small
            destinationPath: c:\app\data
..
```

which compiles to ARM as per docs:

```json
…
                  "volumes": [
                    {
                      "name": "sfvol",
                      "creationParameters": {
                        "kind": "ServiceFabricVolumeDisk",
                        "sizeDisk": "small"
                      },
                      "destinationPath": "c:\\app\\data"
                    }
                  ],
...
```
